apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        rm -rf node_modules
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  steps:
    - name: run-jest-tests
      image: node:18
      script: |
        npm install
        npx jest --passWithNoTests
